
[package]
authors = ["Shyam. M <shayammurali@gmail.com>"]
edition = "2021"
name = "brahma-core"
version = "1.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
bytes = "1"
http-body-util = "0.1"
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
napi = { version = "3.0.0", features = ["async", "tokio_rt", "serde-json"] } 
napi-derive = "3.0.0"
once_cell = "1.21.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }



[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
